# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aurellia/Documents/GitHub/fpga-fmcw-radar-processor/vivado_proj/fmcw_radar_core/fmcw_radar_core.srcs/sources_1/ip/xfft_doppler_1/xfft_doppler.xci
# IP: The module: 'xfft_doppler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aurellia/Documents/GitHub/fpga-fmcw-radar-processor/vivado_proj/fmcw_radar_core/fmcw_radar_core.gen/sources_1/ip/xfft_doppler_1/xfft_doppler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_doppler'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Aurellia/Documents/GitHub/fpga-fmcw-radar-processor/vivado_proj/fmcw_radar_core/fmcw_radar_core.srcs/sources_1/ip/xfft_doppler_1/xfft_doppler.xci
# IP: The module: 'xfft_doppler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aurellia/Documents/GitHub/fpga-fmcw-radar-processor/vivado_proj/fmcw_radar_core/fmcw_radar_core.gen/sources_1/ip/xfft_doppler_1/xfft_doppler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_doppler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
